wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.22
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.8
    t:
      1:
      - 1
      4: 3.8.8
      5: 0.10.22
      8:
      - 3
      - 5
batch_size:
  desc: null
  value: 256
buffer_capacity:
  desc: null
  value: 2000
clip_parameter:
  desc: null
  value: 0.1
gamma:
  desc: null
  value: 0.99
learing_rate:
  desc: null
  value: 0.0001
tau:
  desc: null
  value: 0.01
